### ISSUE TITLE
图片尺寸

### ISSUE THREAD

**Issue by fy5220** [lawlite19/Blog-Back-Up#3]
大佬麻烦问下- -.大图我没有按你的脚本弄,我弄的不是正方形的尺寸.而且在ins.js里面的读取所有照片时,你写的data-size="1080x1080" 我改成了图片尺寸.1620*1080..但是到页面显示时就严重失调了..比例差不多成了2:1这种.这是怎么回事?新手小白..打扰了

**Comment by lawlite19** [comment]
改那里应该是没有用的，我也是用的别人的，具体的可能需要改样式

**Comment by fy5220** [comment]
改那里有效果..只不过显示的时候感觉严重失调了- -!还是谢谢了!
