### ISSUE TITLE
创建相册问题

### ISSUE THREAD

**Issue by ctocto** [lawlite19/Blog-Back-Up#4]
你好，向你请教一个问题。
source/photos/index.ejs  文件开头：
`--- 
layout: post 
slug: "photos" 
title: "相册" 
noDate: "true" 
comments: "false" 
---`
有这样一段内容，它在页面是这样显示的
![image](https://user-images.githubusercontent.com/16641120/32408023-51c099f0-c1cc-11e7-9a62-87975fe19609.png)
这是什么原因，请指教，谢谢。

**Comment by lawlite19** [comment]
你自己调调，我也不太清楚，我这边没有这种情况，有可能是格式问题。

**Comment by ctocto** [comment]
好的。谢谢
